# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapMyIndia' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for MapMyIndia
pod 'MapplsMap', '5.13.2'

end
